#!/usr/bin/with-contenv /bin/sh

CONFIG_FILE=${APP_PATH}/conf/dnsmasq_updater.conf

if $(env | grep -q DMU_); then
	[ ! -z "${DMU_IP}" ] && sed -i "s!^ip.*!ip=${DMU_IP}!" $CONFIG_FILE

	[ ! -z "${DMU_DOMAIN}" ] \
		&& { sed -i "s!^domain.*!domain=${DMU_DOMAIN}!" $CONFIG_FILE; } \
		|| sed -i "s!^domain.*!domain=docker!" $CONFIG_FILE

	[ ! -z "${DMU_DOCKER_SOCKET}" ] && sed -i "s!^docker_socket.*!docker_socket=${DMU_DOCKER_SOCKET}!" $CONFIG_FILE
	[ ! -z "${DMU_NETWORK}" ] && sed -i "s!^network.*!network=${DMU_NETWORK}!" $CONFIG_FILE
	[ ! -z "${DMU_SERVER}" ] && sed -i "s!^server.*!server=${DMU_SERVER}!" $CONFIG_FILE

	[ ! -z "${DMU_PORT}" ] \
		&& { sed -i "s!^port.*!port=${DMU_PORT}!" $CONFIG_FILE; } \
		|| sed -i "s!^port.*!port=22!" $CONFIG_FILE

	[ ! -z "${DMU_LOGIN}" ] && sed -i "s!^login.*!login=${DMU_LOGIN}!" $CONFIG_FILE
	[ ! -z "${DMU_PASSWORD}" ] && sed -i "s!^password.*!password=${DMU_PASSWORD}!" $CONFIG_FILE
	[ ! -z "${DMU_KEY}" ] && sed -i "s!^key.*!key=${DMU_KEY}!" $CONFIG_FILE
	[ ! -z "${DMU_REMOTE_FILE}" ] && sed -i "s!^file.*!file=${DMU_REMOTE_FILE}!" $CONFIG_FILE

	[ ! -z "${DMU_REMOTE_CMD}" ] \
		&& { sed -i "s!^remote_cmd.*!remote_cmd=${DMU_REMOTE_CMD}!" $CONFIG_FILE; } \
		|| sed -i "s!^remote_cmd.*!remote_cmd=service restart_dnsmasq!" $CONFIG_FILE

	[ ! -z "${DMU_DELAY}" ] && sed -i "s!^delay.*!delay=${DMU_DELAY}!" $CONFIG_FILE

	sed -i "s!^ready_fd.*!ready_fd=5!" $CONFIG_FILE
fi
