; [general]
; ready_fd=
;
; [dns]
; ip=
;
; [docker]
; docker_socket=unix://var/run/docker.sock
; network=
;
; [api]
; server=
; port=8080
; key=


;; for testing
[general]
ready_fd=

[dns]
ip=192.168.30.50

[docker]
docker_socket=unix://var/run/docker.sock
network=traefik

[api]
server=dmu.moon
port=80
key=APIKEY
