#!/usr/bin/with-contenv /bin/sh
#shellcheck shell=sh

DEBUG_STRING=''

if [ ! -z ${DMU_DEBUG+set} ]; then
	case ${DMU_DEBUG} in
		true|True)
			DEBUG_STRING='--debug'
			;;
	esac
fi

${APP_PATH}/dnsmasq_updater -c ${APP_PATH}/conf/dnsmasq_updater.conf ${DEBUG_STRING}
