#!/usr/bin/env bash

## get the repo and tag strings
#
image_repo=${IMAGE_NAME%:*}
image_tag=${IMAGE_NAME#*:}

## generate and apply extra tags
#
tags=()

if [ "${image_tag}" = "binary" ]; then
        tags+=('latest')
fi

## push the tags
#
push_tags()     {
        for tag in ${tags[@]}; do
                echo '---'
                echo "Adding tag: ${image_repo}:${tag}"
                echo '---'
                docker tag $IMAGE_NAME ${image_repo}:${tag}
                docker push ${image_repo}:${tag}
        done
}

push_tags
