#! /usr/bin/env bash

echo "--- pre_build ---"

## register qemu-*-static for all supported processors except the current one
#
docker run --rm --privileged multiarch/qemu-user-static:register --reset
echo
